version: "3.9"
services:
  ohlc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - DSN=postgresql://root:password@netflake.ckei7oxxizif.us-east-1.rds.amazonaws.com:5432/netflakes?sslmode=disable
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=ohlc
      - DB_URL=postgresql://root:password@netflake.ckei7oxxizif.us-east-1.rds.amazonaws.com:5432/netflakes?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["./wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/ohlc_app"]
    networks:
      - ohlc

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ohlc
    networks:
      - ohlc

networks:
  ohlc:
    driver: bridge
